### ISSUE TITLE
in operator on _id throws "Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters"

### ISSUE THREAD

**Issue by SaikiranDaripelli** [vdemedes/mongorito#106]
When we use in operator on _id, find throws 
Used as : 
```javascript
var listings = yield models.Listings.in("_id",this.query.id).find();
```
Error:

```javascript
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
      at new ObjectID (/Users/saikiran/Work/hack-cm/server/node_modules/mongorito/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid.js:38:11)
      at toObjectId (/Users/saikiran/Work/hack-cm/server/node_modules/mongorito/util/to-objectid.js:26:9)
      at Query.find (/Users/saikiran/Work/hack-cm/server/node_modules/mongorito/lib/query.js:332:20)
      at Object.<anonymous> (/Users/saikiran/Work/hack-cm/server/src/routes/properties.js:207:66)
      at next (native)
      at onFulfilled (/Users/saikiran/Work/hack-cm/server/node_modules/koa/node_modules/co/index.js:65:19)
      at /Users/saikiran/Work/hack-cm/server/node_modules/koa/node_modules/co/index.js:54:5
      at Object.co (/Users/saikiran/Work/hack-cm/server/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.toPromise (/Users/saikiran/Work/hack-cm/server/node_modules/koa/node_modules/co/index.js:118:63)
      at next (/Users/saikiran/Work/hack-cm/server/node_modules/koa/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/saikiran/Work/hack-cm/server/node_modules/koa/node_modules/co/index.js:69:7)
      at process._tickDomainCallback (node.js:411:9)
```

**Comment by ulpian** [comment]
I get the same issue, this is really critical.

**Comment by vdemedes** [comment]
I'm really short of time lately, so a PR would be very welcome!

**Comment by vdemedes** [comment]
```js
var listings = yield models.Listings.in("_id",this.query.id).find();
```

And I think `in()` expects an array: `[this.query.id]`.

**Comment by SaikiranDaripelli** [comment]
this.query.id is an array, i will try to send a PR.

**Comment by ulpian** [comment]
Any update on this?

**Comment by SaikiranDaripelli** [comment]
Sorry Closed by mistake, in attempt to comment.

**Comment by vdemedes** [comment]
I think this PR (https://github.com/vdemedes/mongorito/pull/111) should've fixed it.

**Comment by ulpian** [comment]
Perhaps we can close this issue?

**Comment by vdemedes** [comment]
Could you please confirm it's fixed? It's not yet released on npm, so make sure to use the master branch.

**Comment by ulpian** [comment]
Waiting for pr #118

**Comment by maxfrigge** [comment]
I can confirm that upgrading from 2.0.0 to 2.1.2 fixed this issue for me.

**Comment by vdemedes** [comment]
@maxfrigge thanks!
