### ISSUE TITLE
Node cannot find module mongorito

### ISSUE THREAD

**Issue by intrinsitech** [vdemedes/mongorito#122]
I have installed mongorito via:
`npm install mongorito --save`

When I try to use mongorito in a koa app, I get the npm module not found error. 

I have node v6.2.0.

Any ideas?

**Comment by vdemedes** [comment]
Can you post the exact stack trace?

**Comment by intrinsitech** [comment]
> babel-node --presets es2015 --harmony "src/index.js"

module.js:442                                                                                                                                                           
    throw err;
    ^

Error: Cannot find module 'mongorito'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (index.js:9:1)
    at Module._compile (module.js:541:32)
    at loader (/Users/stephen/code/banjoben/bb-server/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rest/of/path/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by vdemedes** [comment]
Something went wrong during the installation process, it's not a bug in Mongorito and most probably you made a mistake. Consider repeating installation one more time and ensure you are in the right directory.

**Comment by vdemedes** [comment]
Turns out this is npm bug, thanks @intrinsitech! I was not aware of this, so I assumed it was user error. Refer to #123, which provides more details. Closing this in favor of the newer issue.
