### ISSUE TITLE
I don't know why?

### ISSUE THREAD

**Issue by striver-x** [vdemedes/mongorito#30]
That is all of code
```javascript
// test.js   
var Mongorito = require('mongorito')
console.log(Mongorito)
```
I got this error when i perform node --harmony test.js
```
/Users/xiaofeng/working/node/52dachu/node_modules/mongorito/node_modules/monk/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^
TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/xiaofeng/working/node/52dachu/node_modules/mongorito/node_modules/monk/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/xiaofeng/working/node/52dachu/node_modules/mongorito/node_modules/monk/node_modules/mongoskin/lib/admin.js:18:37)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xiaofeng/working/node/52dachu/node_modules/mongorito/node_modules/monk/node_modules/mongoskin/lib/db.js:20:17)
    at Module._compile (module.js:460:26)
```

**Comment by vdemedes** [comment]
What version of Mongorito are you using and what Node.js/io.js version?

**Comment by striver-x** [comment]
Mongorito is v0.6.14  and Node.js is v0.12.0.

**Comment by vdemedes** [comment]
There must be wrong something in your environment, because I have the same versions and it works.
