### ISSUE TITLE
save(...).then is not a function

### ISSUE THREAD

**Issue by AleffHenrique** [vdemedes/mongorito#90]
I tried something similar to the example given on the readme.md file:

```JavaScript
var Mongorito = require('mongorito');
var Model = Mongorito.Model;

Mongorito.connect('mongodb://localhost:27017/cr-test');

class User extends Model {
  collection() {
    return 'users';
  }
}

var user1 = new User({
  name: "James Gosling",
  email: "user1@gmail.com",
  password: "changeme"
});

user1.save().then(() => {
  console.log('User Created');
});
```

when I run ```node --harmony server.js``` I get this error:

```
user1.save().then(() => {
             ^

TypeError: user1.save(...).then is not a function
    at Object.<anonymous> (...\app\server.js:24:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

Could someone explain me how could I fix that?

**Comment by AleffHenrique** [comment]
Well, I know now that its' readme.md file isn't up to date. So would be a improvement update it?

**Comment by vdemedes** [comment]
You are probably using the version from npm, here's the readme for the released version - https://github.com/vdemedes/mongorito/tree/v1.4.6.

The readme in master is for the next-gen Mongorito, which is based on promises (#87).
