### ISSUE TITLE
this is undefined

### ISSUE THREAD

**Issue by wesleycoder** [vdemedes/mongorito#99]
I'm trying to use Babel.js and Koa.js with mongorito.
Running this files gives me the error below in [Line#77](https://github.com/vdemedes/mongorito/blob/master/lib/mongorito.js#L77).
```
/projects/atados/v3/node_modules/mongorito/lib/mongorito.js:77
	if (!this._connection) {
	         ^

TypeError: Cannot read property '_connection' of undefined
    at Mongorito.connect (/projects/atados/v3/node_modules/mongorito/lib/mongorito.js:77:11)
    at Object.<anonymous> (index.js:9:1)
    at Module._compile (module.js:413:34)
    at loader (/projects/atados/v3/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/projects/atados/v3/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/projects/atados/v3/index.js:9:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
```
My index.js file:
```
require('babel-register')({
	presets: ['es2015-node5'],
	plugins: [
		'transform-async-to-generator'
	],
	extensions: ['.jsx', '.js']
});
require('./server');
```
My server.js file:
```
'use strict';
import {connect} from 'mongorito';
import Koa from 'koa';

connect('localhost/test');

let app = new Koa();
app.listen(port);

app.on('close', function * () {
	yield mongorito.disconnect();
});
```

**Comment by vdemedes** [comment]
`connect` property is not bound to `mongorito`, so when you `connect()` instead of `mongorito.connect()`, the context is `undefined`.

**Comment by wesleycoder** [comment]
Oh, thanks!
